Feature/aos 3980 newclient
Skatteetaten/gorg pull request #19
Opened 2020-02-19 11:13 UTC by Aerlant

2020-02-19 11:15 UTC, Aerlant commented on src/main/resources/application.yaml
> +kubernetes:
Ser denne ikke var helt oppdatert. Må kanskje finne en annen måte å definere disse

2020-04-01 12:12 UTC, bjartek commented
This needs to use the latest version of the kubernetes client.

2020-06-03 11:23 UTC, bjartek requested changes

2020-06-03 11:23 UTC, bjartek commented on src/main/kotlin/no/skatteetaten/aurora/gorg/model/ApplicationDeployment.kt
> +) : SkatteetatenCRD("ApplicationDeployment") {
Check this versus the one that is in mokey.

2020-07-13 11:12 UTC, jarlehansen commented
Skjer det noe mer med denne? Ser at gorg ikke har http client metrikker, noe vi bør fikse.

2020-07-28 08:04 UTC, merged