Feature/aos 2760 oppdater gorg etter application deployment
Skatteetaten/gorg pull request #8
Opened 2018-10-23 12:16 UTC by Aerlant

Readme :)

2018-10-23 13:16 UTC, bjartek requested changes
Det er noen plasser man fremdeles bruker ttl, det skal vel være removeAfter overalt? 

Ellers ser det veldig greit ut :)

Det kan diskuteres om man trenger dry run eller ikke. Man kan jo hente ut listen av midlertidige applikasjoner hvis man vil.

2018-10-23 13:16 UTC, bjartek commented on src/main/kotlin/no/skatteetaten/aurora/gorg/extensions/ObjectMetadata.kt
> +    } ?: throw IllegalStateException("ttl is not set or valid timstamp")
Denne skal vel si removeAfter ikke ttl?

2018-10-23 13:16 UTC, bjartek commented on src/main/kotlin/no/skatteetaten/aurora/gorg/extensions/ObjectMetadata.kt
> +    } ?: throw IllegalStateException("ttl is not set or valid timstamp")
removeAfter ikke ttl

2018-10-23 13:16 UTC, bjartek commented on src/main/kotlin/no/skatteetaten/aurora/gorg/service/ApplicationDeploymentService.kt
> +class ApplicationDeploymentService(val client: DefaultOpenShiftClient, @Value("\${dryrun}") val dryrun: Boolean) {
dryrun bør ekspneres under gobo.dryrun

2018-10-23 13:16 UTC, bjartek commented on src/main/kotlin/no/skatteetaten/aurora/gorg/service/ApplicationDeploymentService.kt
> +        } else {
Her ville jeg heller returnert tidlig enn å ha en else blokk. Da blir koden flatere.

2018-10-23 13:16 UTC, bjartek commented on src/test/kotlin/no/skatteetaten/aurora/gorg/testDataBuilders.kt
> +    val dcTtl: Instant = Instant.now().plusSeconds(60)
dcRemoveAfter?

2018-10-23 13:16 UTC, bjartek commented on src/test/kotlin/no/skatteetaten/aurora/gorg/testDataBuilders.kt
> +                labels = mapOf("ttl" to dcTtl.epochSecond.toString())
Dette blir vel feil? Skal ikke dette være removeAfter?

2018-10-24 06:15 UTC, bjartek commented on src/main/kotlin/no/skatteetaten/aurora/gorg/service/DeleteService.kt
> +    fun deleteResource(item: TemporaryResource, deleteFunction: (TemporaryResource) -> Boolean): Boolean {
Hmm jeg kom plutselig til å tenke på, er det rett at denne funksjonen skal ha deleteFunction som (TemporaryResource) -> Boolean?

Burde den heller hatt DefaultOpenshiftClient som parameter. Da kunne man kalt deleteService rett fra kontroll laget som dette.

```
deleteService.deleteResource(resource) { client ->
   client....(resource.namespace, resource.name)
}

```

2018-10-25 10:02 UTC, Aerlant commented on src/main/kotlin/no/skatteetaten/aurora/gorg/service/ApplicationDeploymentService.kt
> +class ApplicationDeploymentService(val client: DefaultOpenShiftClient, @Value("\${dryrun}") val dryrun: Boolean) {
dryrun renama til deleteResources og koden reformattert.

2018-10-25 10:03 UTC, Aerlant commented on src/test/kotlin/no/skatteetaten/aurora/gorg/testDataBuilders.kt
> +    val dcTtl: Instant = Instant.now().plusSeconds(60)
vi har ikke sett på testene ennå pga. refaktorisering

2018-10-25 10:03 UTC, Aerlant commented on src/main/kotlin/no/skatteetaten/aurora/gorg/service/DeleteService.kt
> +    fun deleteResource(item: TemporaryResource, deleteFunction: (TemporaryResource) -> Boolean): Boolean {
Skal være implementert i siste commit.

2018-10-26 13:36 UTC, closed without merging